In [22]:
import seaborn as sns 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [23]:
df=pd.read_csv("/Users/mayurimamdi/Downloads/customer_subscription_churn_usage_patterns.csv")

In [24]:
df.head()

,user_id,signup_date,plan_type,monthly_fee,avg_weekly_usage_hours,support_tickets,payment_failures,tenure_months,last_login_days_ago,churn
0,1,2023-04-15,Premium,699,1.1,4,1,8,14,Yes
1,2,2023-08-27,Premium,699,2.6,6,0,35,1,Yes
2,3,2023-10-12,Premium,699,14.3,8,3,2,14,Yes
3,4,2023-12-11,Basic,199,17.6,5,2,11,9,Yes
4,5,2023-02-14,Basic,199,9.8,5,2,6,38,Yes

In [25]:
df.shape

(2800, 10)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2800 entries, 0 to 2799
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   user_id                 2800 non-null   int64
 1   signup_date             2800 non-null   object
 2   plan_type               2800 non-null   object
 3   monthly_fee             2800 non-null   int64
 4   avg_weekly_usage_hours  2800 non-null   float64
 5   support_tickets         2800 non-null   int64
 6   payment_failures        2800 non-null   int64
 7   tenure_months           2800 non-null   int64
 8   last_login_days_ago     2800 non-null   int64
 9   churn                   2800 non-null   object
dtypes: float64(1), int64(6), object(3)
memory usage: 218.9+ KB

In [27]:
df['plan_type'].value_counts()

plan_type
Premium     944
Standard    933
Basic       923
Name: count, dtype: int64

In [28]:
df['monthly_fee'].value_counts()

monthly_fee
699    944
399    933
199    923
Name: count, dtype: int64

In [29]:
df['churn'].value_counts()

churn
Yes    1605
No     1195
Name: count, dtype: int64

In [43]:
df['signup_year']=df['signup_date'].str.split('-').str[0].astype(int)

In [44]:
df['signup_month']=df['signup_date'].str.split('-').str[1].astype(int)

In [45]:
df['day']=df['signup_date'].str.split('-').str[2].astype(int)

In [33]:
df.head()

,user_id,signup_date,plan_type,monthly_fee,avg_weekly_usage_hours,support_tickets,payment_failures,tenure_months,last_login_days_ago,churn,signup_year,signup_month,day
0,1,2023-04-15,Premium,699,1.1,4,1,8,14,Yes,2023,04,15
1,2,2023-08-27,Premium,699,2.6,6,0,35,1,Yes,2023,08,27
2,3,2023-10-12,Premium,699,14.3,8,3,2,14,Yes,2023,10,12
3,4,2023-12-11,Basic,199,17.6,5,2,11,9,Yes,2023,12,11
4,5,2023-02-14,Basic,199,9.8,5,2,6,38,Yes,2023,02,14

## EDA

In [34]:
#df['churn']=df['churn'].map({'Yes':1, 'No':0})

In [35]:
#df['plan_type']=df['plan_type'].map({'Premium':3, 'Standard':2, 'Basic':1})

In [37]:
df['signup_year'].unique()

array(['2023', '2024'], dtype=object)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2800 entries, 0 to 2799
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   user_id                 2800 non-null   int64
 1   signup_date             2800 non-null   object
 2   plan_type               2800 non-null   object
 3   monthly_fee             2800 non-null   int64
 4   avg_weekly_usage_hours  2800 non-null   float64
 5   support_tickets         2800 non-null   int64
 6   payment_failures        2800 non-null   int64
 7   tenure_months           2800 non-null   int64
 8   last_login_days_ago     2800 non-null   int64
 9   churn                   2800 non-null   object
 10  signup_year             2800 non-null   object
 11  signup_month            2800 non-null   object
 12  day                     2800 non-null   object
dtypes: float64(1), int64(6), object(6)
memory usage: 284.5+ KB

In [40]:
res=df[df['signup_year']==2023].groupby('signup_year')['churn'].value_counts().max()